apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: observability

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.5.1
      helm:
        valueFiles:
          - $values/gitops/apps/platform/observability/alloy/values/values.yaml
          - $values/gitops/apps/platform/observability/alloy/values/values-dev.yaml

    - repoURL: https://github.com/LaurisNeimanis/gitops-observability-stack.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
