apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-rules
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: observability
  source:
    repoURL: https://github.com/LaurisNeimanis/gitops-observability-stack.git
    targetRevision: main
    path: gitops/apps/platform/observability/prometheus-rules
  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
